management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: user-service-provider
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:localhost}:8848

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    # register-mode: interface
    address: nacos://${NACOS_SERVER:localhost}:8848
    # username: nacos
    # password: nacos
    group: DEFAULT_GROUP
    parameters:
      register-consumer-url: true # 注册接口级消费者

#  protocol:
#    name: dubbo
#    port: -1
