server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: user-service-consumer-ali
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:localhost}:8848

service-url:
  nacos-user-service: http://user-service-ali