server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: user-service-consumer-ali
  cloud:
    nacos:
      discovery:
        server-addr: localhost:58848

service-url:
  nacos-user-service: http://user-service-ali