server:
  port: 8082
spring:
  application:
    name: ribbon-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
user-service:
  ribbon:
    listOfServers: localhost:8080,localhost:8081