version: '3'
services:
  user-service-ali:
    image: F.LuVx/user-service-ali:latest
    container_name: user-service-ali
    build:
      dockerfile: ./user-service-ali/Dockerfile
      context: ../
    ports:
      - "8080:8080"
    extra_hosts:
      - luvx:127.0.0.1

  user-service-consumer-ali:
    image: F.LuVx/user-service-consumer-ali:latest
    container_name: user-service-consumer-ali
    build:
      dockerfile: ./user-service-consumer-ali/Dockerfile
      context: ../
    ports:
      - "8081:8080"
    extra_hosts:
      - luvx:127.0.0.1
