version: '3'
services:
  user-service-ali-0:
    image: F.LuVx/user-service-ali:latest
    container_name: user-service-ali-0
    networks:
      - net_common
    build:
      dockerfile: ./user-service-ali/Dockerfile
      context: ./
    ports:
      - "8081:8081"
    env_file:
      - ./env.env
#    extra_hosts:
#      - luvx:127.0.0.1

  user-service-ali-1:
    image: F.LuVx/user-service-ali:latest
    container_name: user-service-ali-1
    networks:
      - net_common
    ports:
      - "18081:8081"
    env_file:
      - ./env.env

  user-service-dubbo-0:
    image: F.LuVx/user-service-dubbo:latest
    container_name: user-service-dubbo-0
    networks:
      - net_common
    build:
      dockerfile: ./user-service-dubbo/user-service-provider/Dockerfile
      context: ./
    env_file:
      - ./env.env

  user-service-dubbo-1:
    image: F.LuVx/user-service-dubbo:latest
    container_name: user-service-dubbo-1
    networks:
      - net_common
    env_file:
      - ./env.env

  user-service-consumer-ali:
    image: F.LuVx/user-service-consumer-ali:latest
    container_name: user-service-consumer-ali
    networks:
      - net_common
    build:
      dockerfile: ./user-service-consumer-ali/Dockerfile
      context: ./
    ports:
      - "8082:8082"
    env_file:
      - ./env.env
    depends_on:
      - user-service-ali-0
      - user-service-ali-1

networks:
  net_common:
    external: true
