server:
  port: 8083

spring:
  application:
    name: user-service-consumer-ribbon

#user-service:
#  ribbon:
#    listOfServers: localhost:8081,localhost:8082

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"