server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/LuVx/spring-cloud.git
          #仓库名
          search-paths:
            - spring-cloud
          force-pull: true
          # username:
          # password:
          default-label: master
#      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/